### ISSUE TITLE
Script is spiking IATI API Gateway capacity

### ISSUE THREAD

**Issue by nosvalds** [devinit/iati-budgets#1]
Hey @dean-breed, since how quickly this runs isn't super important for your purposes, would you be willing to slow down the pagination by changing this to 1sec or something similar? Then we can see if that reduces the load on our API Gateway?

https://github.com/devinit/iati-budgets/blob/5a85e3386d99e45f476898437e9db0211ef474a6/iati_marker.R#L34

**Comment by dean-breed** [comment]
No problem at all. I'll do that now

**Comment by dean-breed** [comment]
I have made this change. Let me know if it is still causing a load issue
